window.TI_CITIES=[
{pl:'Praga',en:'Prague',v:20.8},{pl:'Wiedeń',en:'Vienna',v:20.1},{pl:'Wrocław',en:'Wrocław',v:19.2},{pl:'Poznań',en:'Poznań',v:18.7},
{pl:'Gdańsk',en:'Gdańsk',v:18.4},{pl:'Budapeszt',en:'Budapest',v:17.9},{pl:'Kraków',en:'Kraków',v:17.2},{pl:'Warszawa',en:'Warsaw',v:17.0,hl:true},
{pl:'Berlin',en:'Berlin',v:16.6},{pl:'Łódź',en:'Łódź',v:16.1,flag:'gaps'},{pl:'Wilno',en:'Vilnius',v:15.8,flag:'thin'},{pl:'Bratysława',en:'Bratislava',v:15.2}];
window.TI_COPY={
pl:{nav:[['#ranking','Ranking'],['#mapa','Mapa'],['#ograniczenia','Metodologia']],night:'Wydanie nocne',day:'Wydanie dzienne',
 hero:{kicker:'Wydanie 01 · wrzesień 2026',title:'Jak naprawdę jeździ komunikacja miejska',lead:'Prędkość autobusów i tramwajów w 12 miastach, policzona z pozycji pojazdów — nie z rozkładu.',value:'17,6',label:'mediana zmierzonej prędkości autobusów i tramwajów, 12 miast',cta1:'Zobacz ranking',cta2:'Otwórz mapę',stamp:['Wydanie','01','09 · 2026']},
 num:{kicker:'02 · Liczba',value:'−22%',title:'Tyle wolniej jadą pojazdy niż najszybsze przejazdy tych samych odcinków.',body:'Odcinek to fragment trasy między dwoma kolejnymi przystankami. Dla każdego porównujemy medianę zmierzonej prędkości z 10% najszybszych przejazdów.',stops:['Rondo ONZ','Rondo Daszyńskiego','Płocka','Młynarska','Wola Ratusz','Os. Górczewska'],speeds:[11.2,8.9,14.6,19.3,12.8],kpis:[['12','miast'],['3,8 mln','pozycji pojazdów dziennie'],['41 200','odcinków']]},
 rank:{kicker:'03 · Ranking',title:'Miasta według zmierzonej prędkości',note:'Mediana dla autobusów i tramwajów, dni robocze 6:00–20:00. Flagi oznaczają ograniczenia danych.',thin:'mała próba',gaps:'luki w danych',more:'Pełny ranking i pobieranie'},
 map:{kicker:'04 · Mapa',title:'Każdy odcinek w kolorze swojej prędkości',body:'Pełnoekranowa mapa pokazuje wszystkie odcinki między przystankami. Poniżej podgląd schematyczny, nie rzeczywista sieć.',cta:'Otwórz mapę Warszawy',legend:{title:'Prędkość',slow:'wolniej',fast:'szybciej',nd:'brak danych',thin:'mała próba'}},
 lim:{kicker:'05 · Uczciwie',title:'Czego te dane nie mówią',items:[['To rekonstrukcja.','Pojazdy raportują pozycję co 10–30 s. Przejazd między odczytami odtwarzamy — nie mierzymy go wprost.'],['Nie każdy odcinek ma próbę.','Odcinki z mniej niż 30 przejazdami oznaczamy kreskowaniem i nie wliczamy do rankingu.'],['Strumienie mają luki.','Gdy operator nie publikuje danych GTFS-Realtime, odcinek jest szary, a miasto dostaje flagę.'],['Rozkład nie jest wzorcem.','Spowolnienie liczymy względem szybkich przejazdów. Rozkład pokazujemy obok, dla porównania.']],links:[['Metodologia','menu_book'],['Jakość danych','fact_check']]},
 foot:{kicker:'Stacja końcowa',ed:'Wydania',eds:['Wydanie 01 · wrzesień 2026 — bieżące'],dl:'Pobierz',dls:['Ranking (CSV)','Odcinki (GeoPackage)','Profile godzinowe (CSV)'],about:'O projekcie',abouts:['Metodologia','Jakość danych','Kontakt'],note:'Wszystkie liczby na tej stronie są poglądowe.'}},
en:{nav:[['#ranking','Ranking'],['#mapa','Map'],['#ograniczenia','Methodology']],night:'Night edition',day:'Day edition',
 hero:{kicker:'Edition 01 · September 2026',title:'How public transport really moves',lead:'Bus and tram speeds in 12 cities, computed from vehicle positions — not from timetables.',value:'17.6',label:'median measured speed of buses and trams, 12 cities',cta1:'See the ranking',cta2:'Open the map',stamp:['Edition','01','09 · 2026']},
 num:{kicker:'02 · The number',value:'−22%',title:'That is how much slower vehicles run than the fastest trips on the same stretches.',body:'A stretch is the part of a route between two consecutive stops. For each one we compare the median measured speed with the fastest 10% of trips.',stops:['Rondo ONZ','Rondo Daszyńskiego','Płocka','Młynarska','Wola Ratusz','Os. Górczewska'],speeds:[11.2,8.9,14.6,19.3,12.8],kpis:[['12','cities'],['3.8 M','vehicle positions a day'],['41,200','stretches']]},
 rank:{kicker:'03 · Ranking',title:'Cities by measured speed',note:'Median for buses and trams, weekdays 6:00–20:00. Flags mark data limitations.',thin:'thin sample',gaps:'feed gaps',more:'Full ranking and downloads'},
 map:{kicker:'04 · Map',title:'Every stretch coloured by its speed',body:'The full-screen map shows every stretch between stops. Below is a schematic preview, not the real network.',cta:'Open the Warsaw map',legend:{title:'Speed',slow:'slower',fast:'faster',nd:'no data',thin:'thin sample'}},
 lim:{kicker:'05 · Honestly',title:'What these data don’t tell you',items:[['It is a reconstruction.','Vehicles report their position every 10–30 s. We rebuild the trip between pings — we don’t measure it directly.'],['Not every stretch has a sample.','Stretches with fewer than 30 trips are hatched and left out of the ranking.'],['Feeds have gaps.','When an operator doesn’t publish GTFS-Realtime, the stretch is grey and the city is flagged.'],['The timetable is not the benchmark.','Slowdown is measured against fast trips. The timetable is shown alongside for comparison.']],links:[['Methodology','menu_book'],['Data quality','fact_check']]},
 foot:{kicker:'Terminus',ed:'Editions',eds:['Edition 01 · September 2026 — current'],dl:'Download',dls:['Ranking (CSV)','Stretches (GeoPackage)','Hourly profiles (CSV)'],about:'About',abouts:['Methodology','Data quality','Contact'],note:'All figures on this page are illustrative.'}}
};
