"""Generate design/tokens.css from design/tokens.json.

Emits only the idx- layer (plus --font-*). GISBoost tokens (bg, ink, accent, read...) come
from gisboost-1.css and are never redeclared here. Theming follows gisboost-1.css: light in
:root, dark via prefers-color-scheme and :root[data-theme="dark"].
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
T = json.loads((ROOT / "design/tokens.json").read_text(encoding="utf-8"))
ALIAS = re.compile(r"^\{([\w.-]+)\}$")

LIGHT, DARK = (t["id"] for t in T["color"]["themes"])
FAMILIES = ["color", "spacing", "radius", "line", "threshold", "duration", "easing", "shadow"]
names = {t["name"] for f in FAMILIES for t in T[f]["tokens"]}


def css(v):
    m = ALIAS.match(v)
    if m:
        assert m[1] in names, f"alias to missing token: {v}"
        return f"var(--{m[1]})"
    return v


root, dark = [], []
for f in FAMILIES:
    for t in T[f]["tokens"]:
        if not t["name"].startswith("idx-"):
            continue
        v = t["value"]
        if isinstance(v, dict):
            root.append(f"--{t['name']}:{css(v[LIGHT])};")
            dark.append(f"--{t['name']}:{css(v[DARK])};")
        else:
            root.append(f"--{t['name']}:{css(v)};")
root += [f"--font-{k}:{v};" for k, v in T["type"]["families"].items()]

styles = [
    f".{s['name']}{{font-family:var(--font-{s['family']});font-size:{s['fontSize']};"
    f"line-height:{s['lineHeight']};font-weight:{s['fontWeight']};letter-spacing:{s['letterSpacing']};}}"
    for g in T["type"]["groups"]
    for s in g["styles"]
]

out = [
    "/* Generated by tools/gen_tokens.py from design/tokens.json. Do not edit. */",
    ":root{" + "".join(root) + "}",
    '@media (prefers-color-scheme: dark){:root:not([data-theme="light"]){' + "".join(dark) + "}}",
    ':root[data-theme="dark"]{' + "".join(dark) + "}",
    *styles,
]
with open(ROOT / "design/tokens.css", "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(out) + "\n")
print(f"design/tokens.css: {len(root)} root, {len(dark)} dark, {len(styles)} type styles")
